### ISSUE TITLE
Broken assimp import

### ISSUE THREAD

**Issue by Guerra24** [Epark012/OpenTK-Practice#1]
Hello!

Just saw your post from reddit and I think the issue is here https://github.com/Epark012/OpenTK-Practice/blob/806f0262a4fe16713c5c87a87127569ea75e46a3/OpenTK-ShaderRenderer/Core/Mesh.cs#L50

It should be
```cs
GL.VertexAttribPointer(2, 2, VertexAttribPointerType.Float, false, Vertex.Stride, 6 * sizeof(float));
```
since it is for texture coords and those are Vec2.

EDIT:

This causes a mismatch with the stride https://github.com/Epark012/OpenTK-Practice/blob/806f0262a4fe16713c5c87a87127569ea75e46a3/OpenTK-ShaderRenderer/Core/Mesh.cs#L113

**Comment by Epark012** [comment]
I changed my code to your line, but still not fix the issue, but that was a stupid mistake. 
GL.VertexAttribPointer(2, 2, VertexAttribPointerType.Float, false, Vertex.Stride, 6 * sizeof(float));

**Comment by Guerra24** [comment]
So that was an absolute pain to debug... Let me clean this up and I will let you know the issue.

![image](https://github.com/Epark012/OpenTK-Practice/assets/9023392/687c8f43-962f-4325-92fb-0f42f6c70a9f)

**Comment by Epark012** [comment]
Thank you so much !

**Comment by Guerra24** [comment]
I believe that's it, just be aware that the light cubes indices are wrong, but that aside it should work.

![image](https://github.com/Epark012/OpenTK-Practice/assets/9023392/90abea0d-b830-4e15-854b-b1e54df81e6d)
![image](https://github.com/Epark012/OpenTK-Practice/assets/9023392/2477e809-6d4c-4c90-9202-cfc91c25ed1e)
![image](https://github.com/Epark012/OpenTK-Practice/assets/9023392/e4b8ac3a-343c-42fd-a43b-594cf63a9ac9)
